language: python

python:
  - 2.7
  - 3.5
  - 3.6

#before_install:
#  - git clone git@github.com:RWTH-EBC/uesgraphs.git
#  - git clone git@github.com:RWTH-EBC/pyCity.git

install:
# - pip install -r requirements.txt
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install networkx
  - pip install xlrd
  - pip install utm
  - pip install pypower
  - pip install shapely
  - pip install pyproj
#  - pip install -e uesgraphs
  - pip install -e git+git@github.com:RWTH-EBC/pyCity.git#egg=pyCity
  - pip install -e .
  - pip install pytest-cov
  - pip install coveralls
  - pip install flake8

script: pytest

after_success:
  - coveralls
