language: python
matrix:
    include:
        - python: 2.7
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install networkx
  - pip install xlrd
  - pip install utm
  - pip install pypower
  - pip install sklearn
  - pip install shapely
  - pip install pyproj
  - pip install pyDOE
  - pip install -e git+git@github.com:RWTH-EBC/TEASER.git@issue297_vdi_core_dev_jsc#egg=teaser
  - pip install -e git+git@github.com:RWTH-EBC/uesgraphs.git#egg=uesgraphs
  - pip install -e git+git@github.com:RWTH-EBC/richardsonpy.git#egg=richardsonpy
  - pip install -e git+git@github.com:RWTH-EBC/pyCity.git@master#egg=pyCity
  - pip install -e .
  - pip install pytest-cov
  - pip install coveralls
  - pip install flake8

script:
  - py.test

after_success:
  - coveralls
